apiVersion: v2
name: http-https-echo
description: A Helm chart that deploys a docker image that echoes request data as JSON; listens on HTTP/S, useful for debugging.
type: application
version: 1.0.0
appVersion: "1.0.0"
