apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "http-https-echo.fullname" . | quote }}
  labels:
    {{- include "http-https-echo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "http-https-echo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "http-https-echo.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: HTTP_PORT
              value: {{ .Values.service.httpPort | quote }}
            - name: HTTPS_PORT
              value: {{ .Values.service.httpsPort | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: https
              containerPort: {{ .Values.service.httpsPort }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
