{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "http-https-echo.fullname" . | quote }}
  labels:
    {{- include "http-https-echo.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if .Values.ingress.tls.caCertificate }}
  tls.crt: {{ (printf "%v\n%v" .Values.ingress.tls.certificate .Values.ingress.tls.caCertificate) | b64enc }}
  {{- else }}
  tls.crt: {{ .Values.ingress.tls.certificate | b64enc }}
  {{- end }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
{{- end }}
