apiVersion: v1
kind: Service
metadata:
  name: {{ include "http-https-echo.fullname" . | quote }}
  labels:
    {{- include "http-https-echo.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
  selector:
    {{- include "http-https-echo.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type | quote }}
